version: '3'

services:

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
#    hostname: mariadb.prototype.springboot.local
    environment:
      MYSQL_DATABASE: ${SPRING_APP_DATABASE_SCHEMA}
      MYSQL_USER: ${SPRING_APP_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_APP_DATABASE_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'R007pwd'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${SPRING_APP_DATABASE_PORT}:3306
#    expose:
      # Opens ports 3306 on the container
#      - '3306'
    volumes:
      - prototype-mariadb-vol:/var/lib/mysql
    networks:
      - prototype-net

#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGODB_REPLICA_SET_MODE: primary
#      MONGO_REPLICA_SET_NAME: rs0
#      MONGO_INITDB_DATABASE: gdl-db
#    command: mongod --replSet rs0 --dbpath /data/db --port 27017 --bind_ip_all
#    volumes:
#      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    expose:
#      - 27017
#    ports:
#      - "27017:27017"
#    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

networks:
  prototype-net:

volumes:
  prototype-mariadb-vol:
