spring:
  config:
    import: ${SPRING_CONFIGSERVER_IMPORT:optional:configserver:https://configserver.deiv70.site:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: ${SPRING_PROFILES_INCLUDE:jdbc}
