spring:
  config:
    import: optional:configserver:https://configserver.deiv70.site:8888

#  docker:
#    compose:
#      enabled: false
#      enabled: true
#      file: compose.yaml
#      lifecycle-management: start_and_stop

  datasource:
    ## JDBC or R2DBC for Reactive
    url: jdbc:${SPRING_APP_DATABASE:mariadb}://${SPRING_APP_DATABASE_HOST:localhost}:${SPRING_APP_DATABASE_PORT:3306}/${SPRING_APP_DATABASE_SCHEMA:prototype}
    username: ${SPRING_APP_DATABASE_USERNAME:spring}
    password: ${SPRING_APP_DATABASE_PASSWORD:spring.pwd}
    driver-class-name: ${SPRING_APP_DATABASE_DRIVER:org.mariadb.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_APP_DATABASE_DDL-AUTO:update}
    properties:
      hibernate:
        dialect: ${SPRING_APP_DATABASE_DIALECT:org.hibernate.dialect.MariaDBDialect}

  security:
    user:
      password: ${SPRING_APP_SECURITY_PASSWORD:2f2489d8-0b33-4eea-a2e1-2bcc57c2826e}
  ## Reactive
#  webflux:
#    base-path: /
#  r2dbc:
#    pool:
#      enabled: true
#      initial-size: 10
#      max-size: 10

logging:
  level:
    root: info
    sql: debug
    org.hibernate: debug
    org.hibernate.SQL: debug
    org.hibernate.stat: debug
#    web: info
#    org.springframework.web: info

## Custom ConditionalOnProperty values
cop:
  database-service: ${SPRING_APP_DATABASE_IMPLEMENTATION:jpa}

## Custom Values for Variables
#vars:
#  db:
#    table-name: ${SPRING_APP_DATABASE_TABLE:prototype}

springdoc:
#  version: '@springdoc.version@'
  show-actuator: true
  use-management-port: true
#  packages-to-scan: site.deiv70.springboot.openapitools, site.deiv70.springboot.application, site.deiv70.springboot.model, vnd.spring-boot.actuator
  swagger-ui:
    enabled: true
    path: ${SPRING_APP_ENDPOINT_SWAGGER:/swagger-ui}
    csrf:
      enabled: true
  api-docs:
    path: /api-docs
#  group-configs:
#    - group: pet
#      paths-to-match: /pet/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: ${SPRING_APP_ENDPOINT_MANAGEMENT_PATH:/actuator}

  server:
    port: ${SPRING_APP_MANAGEMENT_PORT:9090}

server:
  port: ${SPRING_APP_PORT:8080}
#  servlet:
#    context-path: ${SPRING_APP_ENDPOINT_CONTEXT_PATH:/}
