openapi: 3.0.3
info:
  title: Swagger Prototype - OpenAPI 3.0
  description: |-
    This is a sample API definition
  contact:
    email: david.gomez.garcia.000@gmail.com
#  termsOfService: http://swagger.io/terms/
#  license:
#    name: Apache 2.0
#    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: http://localhost:8080/api

tags:
  - name: prototype
    description: Everything about Prototypes
    externalDocs:
      description: Find out more
      url: http://swagger.io

paths:
  /prototypes:
    post:
      tags:
        - prototype
      summary: Add Prototypes
      description: Add one or some New Prototypes
      operationId: addPrototypes
      requestBody:
        $ref: '#/components/requestBodies/PrototypeApiCreateRequestList'
      responses:
        '200':
          $ref: '#/components/responses/PrototypeApiResponseList'
        '400':
          description: Invalid Request
    #      security:
    #        - petstore_auth:
    #            - write:pets
    #            - read:pets

    get:
      x-spring-paginated: true
      tags:
        - prototype
      summary: Get Prototypes
      description: Multiple name values can be provided with comma separated strings
      operationId: getPrototypes
      parameters:
        - name: name
          in: query
          description: Name value for filtering
          required: false
          explode: true
          schema:
            type: string
            example: 'prototype'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrototypeDtoModel'
        '400':
          description: Invalid Request
  #      security:
  #        - petstore_auth:
  #            - write:pets
  #            - read:pets

  /prototypes/{prototypeId}:
    get:
      tags:
        - prototype
      summary: Get Prototype By ID
      description: Returns a single Prototype
      operationId: getPrototypeById
      parameters:
        - $ref: '#/components/parameters/prototypeId_path'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrototypeDtoModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/PrototypeDtoModel'
        '400':
          description: Invalid Request
        '404':
          description: Prototype Not Found
    #      security:
    #        - api_key: []
    #        - petstore_auth:
    #            - write:pets
    #            - read:pets
    put:
      tags:
        - prototype
      summary: Update Prototype By ID
      description: Update an existing Prototype by Id
      operationId: updatePrototypeById
      parameters:
        - $ref: '#/components/parameters/prototypeId_path'
      requestBody:
        description: Prototype Array Request for delete
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PrototypeUpdateDtoModel'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrototypeDtoModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/PrototypeDtoModel'
        '400':
          description: Invalid Request
        '404':
          description: Prototype Not Found
    #      security:
    #        - petstore_auth:
    #            - write:pets
    #            - read:pets
    delete:
      tags:
        - prototype
      summary: Delete Prototype By ID
      description: delete a Prototype
      operationId: deletePrototypeById
      parameters:
        - $ref: '#/components/parameters/prototypeId_path'
      #        - name: api_key
      #          in: header
      #          description: ''
      #          required: false
      #          schema:
      #            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid Request
        '404':
          description: Prototype Not Found
#      security:
#        - petstore_auth:
#            - write:pets
#            - read:pets

#  /prototypes/{prototypeId}/uploadImage:
#    post:
#      tags:
#        - prototype
#      summary: uploads an image
#      description: ''
#      operationId: uploadFile
#      parameters:
#        - name: prototypeId
#          in: path
#          description: ID of pet to update
#          required: true
#          schema:
#            type: integer
#            format: int64
#        - name: additionalMetadata
#          in: query
#          description: Additional Metadata
#          required: false
#          schema:
#            type: string
#      requestBody:
#        content:
#          application/octet-stream:
#            schema:
#              type: string
#              format: binary
#      responses:
#        '200':
#          description: successful operation
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ApiResponseDtoModel'
#      security:
#        - petstore_auth:
#            - write:pets
#            - read:pets

components:

  requestBodies:

    PrototypeApiCreateRequestList:
      description: Prototype Array Request for create
      content:
        application/json:
          schema:
            type:  array
            items:
              $ref: '#/components/schemas/PrototypeDtoModel'

  responses:

    PrototypeApiResponseList:
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PrototypeDtoModel'

  schemas:

    PrototypeDtoModel:
      required:
        - name
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440000
        name:
          type: string
          example: prototype name
        description:
          type: string
          example: This is the description of the prototype
      xml:
        name: 'PrototypeDtoModel'

    PrototypeUpdateDtoModel:
      type: object
      properties:
        name:
          type: string
          example: prototype name
        description:
          type: string
          example: This is the description of the prototype
      xml:
        name: 'PrototypeUpdateDtoModel'

    ApiResponseDtoModel:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: 'ApiResponseDtoModel'

#    Tag:
#      type: object
#      properties:
#        id:
#          type: integer
#          format: int64
#        name:
#          type: string
#      xml:
#        name: tag

  parameters:

    prototypeId_path:
      name: prototypeId
      in: path
      description: ID of Prototype
      required: true
      schema:
        type: string
        format: uuid

    name_notrequired_explode:
      name: name
      in: query
      description: Name value for filtering
      required: false
      explode: true
      schema:
        type: string
        example: 'name'

#  securitySchemes:

#    petstore_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
#          scopes:
#            write:pets: modify pets in your account
#            read:pets: read your pets
#    api_key:
#      type: apiKey
#      name: api_key
#      in: header
